name: Build mp4v2 Library

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake make gcc g++

    - name: Build mp4v2
      run: |
        mkdir build
        cd build
        cmake ..
        make

  - name: List build directory contents
      run: |
        echo "Listing contents of the build directory:"
        ls -R build

    - name: Upload artifacts
      uses: actions/upload-artifact@v3  # Updated to the latest version
      with:
        name: mp4v2
        path: build/**/*.a  # Upload all .a files from the build directory
        if-no-files-found: warn
